#!/usr/bin/env python3
"""
WS8 Daily Generator — Le Tunnel de Babel
Generates multilingual texts that exist in the collision between languages.

Usage:
    python generate.py                    # Generate today's text
    python generate.py --seed le_seuil    # Generate with specific seed
"""

import os
import sys
import json
import random
import datetime
import urllib.request
import urllib.error
import yaml

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATES_PATH = os.path.join(SCRIPT_DIR, "templates.yaml")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "..", "daily")

# API config
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
MODEL = "anthropic/claude-sonnet-4"  # Good multilingual capability


def load_templates():
    with open(TEMPLATES_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def pick_seed(templates, seed_name=None):
    seeds = templates["seeds"]
    if seed_name:
        for s in seeds:
            if s["name"] == seed_name:
                return s
        print(f"Seed '{seed_name}' not found, picking random.")
    today = datetime.date.today()
    # Deterministic but varies: use day-of-year to pick seed
    idx = today.timetuple().tm_yday % len(seeds)
    return seeds[idx]


def build_prompt(seed, templates):
    lang_display = templates["lang_display"]
    lang_names = ", ".join(lang_display.get(l, l) for l in seed["lang_pair"])
    day_of_year = datetime.date.today().timetuple().tm_yday

    prompt = templates["prompt_template"].format(
        description=seed["description"],
        lang_names=lang_names,
    )
    # Replace [n/∞] with actual day number
    prompt = prompt.replace("[n/∞]", f"[{day_of_year}/∞]")
    return prompt


def generate(prompt):
    if not OPENROUTER_API_KEY:
        print("ERROR: OPENROUTER_API_KEY not set")
        sys.exit(1)

    data = json.dumps({
        "model": MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 800,
        "temperature": 0.9,
    }).encode("utf-8")

    req = urllib.request.Request(
        OPENROUTER_URL,
        data=data,
        headers={
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        resp = urllib.request.urlopen(req, timeout=60)
        result = json.loads(resp.read().decode("utf-8"))
        return result["choices"][0]["message"]["content"]
    except urllib.error.HTTPError as e:
        body = e.read().decode() if e.fp else "no body"
        print(f"API Error {e.code}: {body[:300]}")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


def save(text, seed):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    today = datetime.date.today().strftime("%Y-%m-%d")
    filename = f"{today}-{seed['name']}.md"
    filepath = os.path.join(OUTPUT_DIR, filename)

    # Get language display names
    lang_display = {
        "fr": "Français", "en": "English", "zh": "中文",
        "ar": "العربية", "yo": "Yorùbá", "ja": "日本語"
    }
    langs = ", ".join(lang_display.get(l, l) for l in seed["lang_pair"])

    content = f"""---
seed: {seed['name']}
date: {today}
languages: {langs}
concept: "{seed['description']}"
generated: true
---

{text}

---
*Auto-generated by WS8 Daily Generator — Le Tunnel de Babel*
*https://github.com/Mesnildot/wave-seed5*
"""
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Generated: {filepath}")
    return filepath


def main():
    # Parse args
    seed_name = None
    if "--seed" in sys.argv:
        idx = sys.argv.index("--seed")
        if idx + 1 < len(sys.argv):
            seed_name = sys.argv[idx + 1]

    templates = load_templates()
    seed = pick_seed(templates, seed_name)
    print(f"Seed: {seed['name']} — {seed['description']}")
    print(f"Languages: {', '.join(seed['lang_pair'])}")

    prompt = build_prompt(seed, templates)
    text = generate(prompt)
    filepath = save(text, seed)

    print(f"\nDone. Output: {filepath}")


if __name__ == "__main__":
    main()
